# Generated by Django 5.2.11 on 2026-02-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage_url_alter_projectimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
