# Generated by Django 5.2.11 on 2026-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_company_project_status_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_web',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
